[pytest]
pythonpath = blogicum/ .
DJANGO_SETTINGS_MODULE = blogicum.settings
norecursedirs = env/*
<<<<<<< HEAD
addopts = -rE -vv --show-capture=no --disable-warnings -p no:cacheprovider
=======
addopts = -vv -p no:cacheprovider --disable-warnings
>>>>>>> 9589b23700b83ab030eb2dcd4a8a573bcea6f430
testpaths = tests/
python_files = test_*.py
django_debug_mode = true
